version: '3'

services:

  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    hostname: "localhost-mongo"
    networks:
      - blog-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    hostname: "localhost"
    networks:
      - blog-network

volumes:
  mongodb_data:

networks:
  blog-network:
    driver: bridge

